# Generated by Django 3.2.9 on 2022-12-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('date', models.DateTimeField()),
                ('open', models.FloatField(blank=True)),
                ('high', models.FloatField(blank=True)),
                ('low', models.FloatField(blank=True)),
                ('close', models.FloatField(blank=True)),
                ('volume', models.PositiveBigIntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candle',
                'verbose_name_plural': 'Candles',
                'db_table': 'candles',
            },
        ),
        migrations.CreateModel(
            name='UploadedCSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvs', verbose_name='File Name')),
                ('timeframe', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Uploaded CSV File',
                'verbose_name_plural': 'Uploaded CSV Files',
                'db_table': 'uploadedcsvfiles',
            },
        ),
    ]
