# Generated by Django 3.2.9 on 2022-12-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='date',
            field=models.DateField(),
        ),
    ]
