# Generated by Django 3.2.9 on 2022-12-10 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_candle_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 12, 10, 12, 37, 4, 316956, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
