# Generated by Django 3.2.9 on 2022-12-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_candle_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcsvfile',
            name='jsonfile',
            field=models.FileField(default='dummy.json', upload_to='jsonfiles', verbose_name='Download JSON File'),
        ),
    ]
