# Generated by Django 3.2.9 on 2022-12-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_uploadedcsvfile_jsonfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedcsvfile',
            name='jsonfile',
            field=models.FileField(upload_to='jsonfiles', verbose_name='Download JSON File'),
        ),
    ]
